#!/usr/bin/python3
from sys import argv

def factor():
   with open(argv[1]) as f:
      for line in f:
        n = int(line)
        print("{:d}=".format(n), end="")
        if n % 2 == 0:
            print("{}*2".format(n//2))
            continue
        for i in factor(n):
            print("{}*{}".format(n//i, i))
            break
        print()
