#!/usr/bin/python3
from sys import argv
from math import sqrt

def factor():
    with open(argv[1]) as f:
        for line in f:
            num = int(line)
            print("{:d}=".format(num), end="")
            if num % 2 == 0:
                print("{}*2".format(num//2))
                continue
            sqn = int(sqrt(num))
            if sqn % 2 == 0:
                sqn += 1
            for i in range(3, sqn + 1, 2):
                if num % i == 0:
                    print("{}*{}".format(i, num//i))
                    break
            if num % i != 0:
                print("{}={}*1".format(num, num))
             


def factor(n):
    if n % 2 == 0:
        yield 2
        while n % 2 == 0:
            n //= 2
    for i in range(3, int(sqrt(n)) + 1, 2):
        if n % i == 0:
            yield i
            while n % i == 0:
                n //= i
    if n > 2:
        yield n           
